language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-28
    - add-on
    - extra
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true

script:
  - ./gradlew clean build
